---
cog_bundle_version: 2
name: circle
version: "0.1"
commands:
  list:
    executable: "/usr/bin/list.rb"
    documentation: "circle list <project>"
    enforcing: false
    options:
      project:
        type: string
        required: true
  build:
    executable: "/usr/bin/build.rb"
    documentation: "circle build <project> <branch>"
    enforcing: false
    options:
      project:
        type: string
        required: true
      branch:
        type: string
        required: true
  status:
    executable: "/usr/bin/status.rb"
    documentation: "circle status <project> <branch>"
    enforcing: false
    options:
      project:
        type: string
        required: true
      branch:
        type: string
        required: true
templates:
  list:
    slack: "```{{#body}}{{{.}}}\n{{/body}}```"
