---
cog_bundle_version: 2
name: circle
version: "0.1"
commands:
  list:
    executable: "/usr/circle/bin/list.rb"
    documentation: "circle list <project>"
  build:
    executable: "/usr/circle/bin/build.rb"
    documentation: "circle build <project> <branch>"
  status:
    executable: "/usr/circle/bin/status.rb"
    documentation: "circle status <project> <branch>"
templates:
  list:
    slack: "{{#.}}{{build_num}} - {{branch}} - {{status}} - {{author_name}}{{/.}}"
  status:
    slack: "{{status}} - {{stop_time}}"
